/*
 * Coindirect
 * The Coindirect API is offered to all users to make use of our P2P Marketplace, Exchange and Wallets.
 *
 * OpenAPI spec version: 1
 * Contact: support@coindirect.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.coindirect.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.OffsetDateTime;
import org.coindirect.api.model.ChatMember;
import org.coindirect.api.model.EncodedFile;
/**
 * ChatMessage
 */


public class ChatMessage {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("sender")
  private ChatMember sender = null;

  @JsonProperty("receiver")
  private ChatMember receiver = null;

  @JsonProperty("message")
  private String message = null;

  @JsonProperty("file")
  private EncodedFile file = null;

  @JsonProperty("dateCreated")
  private OffsetDateTime dateCreated = null;

  public ChatMessage id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ChatMessage sender(ChatMember sender) {
    this.sender = sender;
    return this;
  }

   /**
   * Get sender
   * @return sender
  **/
  @Schema(description = "")
  public ChatMember getSender() {
    return sender;
  }

  public void setSender(ChatMember sender) {
    this.sender = sender;
  }

  public ChatMessage receiver(ChatMember receiver) {
    this.receiver = receiver;
    return this;
  }

   /**
   * Get receiver
   * @return receiver
  **/
  @Schema(description = "")
  public ChatMember getReceiver() {
    return receiver;
  }

  public void setReceiver(ChatMember receiver) {
    this.receiver = receiver;
  }

  public ChatMessage message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @Schema(description = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public ChatMessage file(EncodedFile file) {
    this.file = file;
    return this;
  }

   /**
   * Get file
   * @return file
  **/
  @Schema(description = "")
  public EncodedFile getFile() {
    return file;
  }

  public void setFile(EncodedFile file) {
    this.file = file;
  }

  public ChatMessage dateCreated(OffsetDateTime dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

   /**
   * Get dateCreated
   * @return dateCreated
  **/
  @Schema(description = "")
  public OffsetDateTime getDateCreated() {
    return dateCreated;
  }

  public void setDateCreated(OffsetDateTime dateCreated) {
    this.dateCreated = dateCreated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatMessage chatMessage = (ChatMessage) o;
    return Objects.equals(this.id, chatMessage.id) &&
        Objects.equals(this.sender, chatMessage.sender) &&
        Objects.equals(this.receiver, chatMessage.receiver) &&
        Objects.equals(this.message, chatMessage.message) &&
        Objects.equals(this.file, chatMessage.file) &&
        Objects.equals(this.dateCreated, chatMessage.dateCreated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, sender, receiver, message, file, dateCreated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatMessage {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("    receiver: ").append(toIndentedString(receiver)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    file: ").append(toIndentedString(file)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
