/*
 * Coindirect
 * The Coindirect API is offered to all users to make use of our P2P Marketplace, Exchange and Wallets.
 *
 * OpenAPI spec version: 1
 * Contact: support@coindirect.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.coindirect.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
/**
 * Fee
 */


public class Fee {
  @JsonProperty("service")
  private BigDecimal service = null;

  @JsonProperty("processing")
  private BigDecimal processing = null;

  public Fee service(BigDecimal service) {
    this.service = service;
    return this;
  }

   /**
   * Get service
   * @return service
  **/
  @Schema(description = "")
  public BigDecimal getService() {
    return service;
  }

  public void setService(BigDecimal service) {
    this.service = service;
  }

  public Fee processing(BigDecimal processing) {
    this.processing = processing;
    return this;
  }

   /**
   * Get processing
   * @return processing
  **/
  @Schema(description = "")
  public BigDecimal getProcessing() {
    return processing;
  }

  public void setProcessing(BigDecimal processing) {
    this.processing = processing;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Fee fee = (Fee) o;
    return Objects.equals(this.service, fee.service) &&
        Objects.equals(this.processing, fee.processing);
  }

  @Override
  public int hashCode() {
    return Objects.hash(service, processing);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Fee {\n");
    
    sb.append("    service: ").append(toIndentedString(service)).append("\n");
    sb.append("    processing: ").append(toIndentedString(processing)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
