/*
 * Coindirect
 * The Coindirect API is offered to all users to make use of our P2P Marketplace, Exchange and Wallets.
 *
 * OpenAPI spec version: 1
 * Contact: support@coindirect.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.coindirect.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * HistoricalDataRequest
 */


public class HistoricalDataRequest {
  @JsonProperty("market")
  private String market = null;

  @JsonProperty("history")
  private String history = null;

  @JsonProperty("grouping")
  private String grouping = null;

  @JsonProperty("limit")
  private Long limit = null;

  @JsonProperty("fill")
  private String fill = null;

  public HistoricalDataRequest market(String market) {
    this.market = market;
    return this;
  }

   /**
   * Get market
   * @return market
  **/
  @Schema(description = "")
  public String getMarket() {
    return market;
  }

  public void setMarket(String market) {
    this.market = market;
  }

  public HistoricalDataRequest history(String history) {
    this.history = history;
    return this;
  }

   /**
   * Get history
   * @return history
  **/
  @Schema(description = "")
  public String getHistory() {
    return history;
  }

  public void setHistory(String history) {
    this.history = history;
  }

  public HistoricalDataRequest grouping(String grouping) {
    this.grouping = grouping;
    return this;
  }

   /**
   * Get grouping
   * @return grouping
  **/
  @Schema(description = "")
  public String getGrouping() {
    return grouping;
  }

  public void setGrouping(String grouping) {
    this.grouping = grouping;
  }

  public HistoricalDataRequest limit(Long limit) {
    this.limit = limit;
    return this;
  }

   /**
   * Get limit
   * @return limit
  **/
  @Schema(description = "")
  public Long getLimit() {
    return limit;
  }

  public void setLimit(Long limit) {
    this.limit = limit;
  }

  public HistoricalDataRequest fill(String fill) {
    this.fill = fill;
    return this;
  }

   /**
   * Get fill
   * @return fill
  **/
  @Schema(description = "")
  public String getFill() {
    return fill;
  }

  public void setFill(String fill) {
    this.fill = fill;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HistoricalDataRequest historicalDataRequest = (HistoricalDataRequest) o;
    return Objects.equals(this.market, historicalDataRequest.market) &&
        Objects.equals(this.history, historicalDataRequest.history) &&
        Objects.equals(this.grouping, historicalDataRequest.grouping) &&
        Objects.equals(this.limit, historicalDataRequest.limit) &&
        Objects.equals(this.fill, historicalDataRequest.fill);
  }

  @Override
  public int hashCode() {
    return Objects.hash(market, history, grouping, limit, fill);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HistoricalDataRequest {\n");
    
    sb.append("    market: ").append(toIndentedString(market)).append("\n");
    sb.append("    history: ").append(toIndentedString(history)).append("\n");
    sb.append("    grouping: ").append(toIndentedString(grouping)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    fill: ").append(toIndentedString(fill)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
