/*
 * Coindirect
 * The Coindirect API is offered to all users to make use of our P2P Marketplace, Exchange and Wallets.
 *
 * OpenAPI spec version: 1
 * Contact: support@coindirect.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.coindirect.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.coindirect.client.model.HistoricalDataRequest;
import org.coindirect.client.model.OHLCV;

/**
 * HistoricalData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-10T11:44:48.559+02:00")
public class HistoricalData {
  @SerializedName("data")
  private List<OHLCV> data = null;

  @SerializedName("metaData")
  private HistoricalDataRequest metaData = null;

  public HistoricalData data(List<OHLCV> data) {
    this.data = data;
    return this;
  }

  public HistoricalData addDataItem(OHLCV dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<OHLCV>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(value = "")
  public List<OHLCV> getData() {
    return data;
  }

  public void setData(List<OHLCV> data) {
    this.data = data;
  }

  public HistoricalData metaData(HistoricalDataRequest metaData) {
    this.metaData = metaData;
    return this;
  }

   /**
   * Get metaData
   * @return metaData
  **/
  @ApiModelProperty(value = "")
  public HistoricalDataRequest getMetaData() {
    return metaData;
  }

  public void setMetaData(HistoricalDataRequest metaData) {
    this.metaData = metaData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HistoricalData historicalData = (HistoricalData) o;
    return Objects.equals(this.data, historicalData.data) &&
        Objects.equals(this.metaData, historicalData.metaData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, metaData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HistoricalData {\n");
    
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    metaData: ").append(toIndentedString(metaData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

