/*
 * Coindirect
 * The Coindirect API is offered to all users to make use of our P2P Marketplace, Exchange and Wallets.
 *
 * OpenAPI spec version: 1
 * Contact: support@coindirect.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.coindirect.api;

import org.coindirect.api.invoker.ApiException;
import org.coindirect.api.model.Market;
import org.coindirect.api.model.OrderBook;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ExchangeApi
 */
@Ignore
public class ExchangeApiTest {

    private final ExchangeApi api = new ExchangeApi();

    /**
     * Get Order Book For Market
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getExchangeOrderBookTest() throws ApiException {
        String symbol = null;
        OrderBook response = api.getExchangeOrderBook(symbol);

        // TODO: test validations
    }
    /**
     * List Markets
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listExchangeMarketsTest() throws ApiException {
        Integer offset = null;
        Integer max = null;
        List<Market> response = api.listExchangeMarkets(offset, max);

        // TODO: test validations
    }
}
