/*
 * Coindirect
 * The Coindirect API is offered to all users to make use of our P2P Marketplace, Exchange and Wallets.
 *
 * OpenAPI spec version: 1
 * Contact: support@coindirect.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.coindirect.api;

import org.coindirect.api.invoker.ApiException;
import org.coindirect.api.model.Errors;
import org.coindirect.api.model.ExchangeOrder;
import org.coindirect.api.model.ExchangeOrderRequest;
import org.coindirect.api.model.Reasons;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ExchangeOrdersApi
 */
@Ignore
public class ExchangeOrdersApiTest {

    private final ExchangeOrdersApi api = new ExchangeOrdersApi();

    /**
     * Place Order
     *
     * Place an Order on the Exchange
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void placeExchangeOrderTest() throws ApiException {
        ExchangeOrderRequest body = null;
        ExchangeOrder response = api.placeExchangeOrder(body);

        // TODO: test validations
    }
    /**
     * List Orders
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listExchangeOrdersTest() throws ApiException {
        String symbol = null;
        Boolean completed = null;
        Integer offset = null;
        Integer max = null;
        List<ExchangeOrder> response = api.listExchangeOrders(symbol, completed, offset, max);

        // TODO: test validations
    }
    /**
     * Check access to market
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMarketAccessTest() throws ApiException {
        String symbol = null;
        Reasons response = api.getMarketAccess(symbol);

        // TODO: test validations
    }
    /**
     * Get Order
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getExchangeOrderTest() throws ApiException {
        String uuid = null;
        ExchangeOrder response = api.getExchangeOrder(uuid);

        // TODO: test validations
    }
    /**
     * Cancel Order
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cancelExchangeOrderTest() throws ApiException {
        String uuid = null;
        ExchangeOrder response = api.cancelExchangeOrder(uuid);

        // TODO: test validations
    }
}
