/*
 * Coindirect
 * The Coindirect API is offered to all users to make use of our P2P Marketplace, Exchange and Wallets.
 *
 * OpenAPI spec version: 1
 * Contact: support@coindirect.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.coindirect.api;

import org.coindirect.api.invoker.ApiException;
import org.coindirect.api.model.PublicAccount;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for P2PVendorInformationApi
 */
@Ignore
public class P2PVendorInformationApiTest {

    private final P2PVendorInformationApi api = new P2PVendorInformationApi();

    /**
     * Get P2P Vendor
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getP2PVendorTest() throws ApiException {
        Long id = null;
        PublicAccount response = api.getP2PVendor(id);

        // TODO: test validations
    }
}
